(defpackage #:webgl-bindings
  (:use :cl :ps)
  #-package-local-nicknames
  (:nicknames #:%webgl #:%gl)
  (:export
   #:active-texture
   #:attach-shader
   #:bind-attrib-location
   #:bind-buffer
   #:bind-framebuffer
   #:bind-renderbuffer
   #:bind-texture
   #:blend-color
   #:blend-equation
   #:blend-equation-separate
   #:blend-func
   #:blend-func-separate
   #:buffer-data
   #:buffer-sub-data
   #:canvas
   #:check-framebuffer-status
   #:clear
   #:clear-color
   #:clear-depth
   #:clear-stencil
   #:color-mask
   #:compile-shader
   #:copy-tex-image-2d
   #:copy-tex-sub-image-2d
   #:create-buffer
   #:create-framebuffer
   #:create-program
   #:create-renderbuffer
   #:create-shader
   #:create-texture
   #:cull-face
   #:delete-buffer
   #:delete-framebuffer
   #:delete-program
   #:delete-renderbuffer
   #:delete-shader
   #:delete-texture
   #:depth-func
   #:depth-mask
   #:depth-range
   #:detach-shader
   #:disable
   #:disable-vertex-attrib-array
   #:draw-arrays
   #:draw-elements
   #:drawing-buffer-height
   #:drawing-buffer-width
   #:enable
   #:enable-vertex-attrib-array
   #:finish
   #:flush
   #:framebuffer-renderbuffer
   #:framebuffer-texture-2d
   #:front-face
   #:generate-mipmap
   #:get-active-attrib
   #:get-active-uniform
   #:get-attached-shaders
   #:get-attrib-location
   #:get-buffer-parameter
   #:get-context-attributes
   #:get-error
   #:get-extension
   #:get-framebuffer-attachment-parameter
   #:get-parameter
   #:get-program-info-log
   #:get-program-parameter
   #:get-renderbuffer-parameter
   #:get-shader-info-log
   #:get-shader-parameter
   #:get-shader-source
   #:get-supported-extensions
   #:get-tex-parameter
   #:get-uniform
   #:get-uniform-location
   #:get-vertex-attrib
   #:get-vertex-attrib-offset
   #:hint
   #:is-buffer
   #:is-context-lost
   #:is-enabled
   #:is-framebuffer
   #:is-program
   #:is-renderbuffer
   #:is-shader
   #:is-texture
   #:line-width
   #:link-program
   #:pixel-store-i
   #:polygon-offset
   #:read-pixels
   #:renderbuffer-storage
   #:sample-coverage
   #:scissor
   #:shader-source
   #:stencil-func
   #:stencil-func-separate
   #:stencil-mask
   #:stencil-mask-separate
   #:stencil-op
   #:stencil-op-separate
   #:tex-image-2d*
   #:tex-image-2d
   #:tex-image2d ;; fixme: delete
   #:tex-parameter-f
   #:tex-parameter-i
   #:tex-sub-image-2d
   #:uniform-1f
   #:uniform-1fv
   #:uniform-1i
   #:uniform-1iv
   #:uniform-2f
   #:uniform-2fv
   #:uniform-2i
   #:uniform-2iv
   #:uniform-3f
   #:uniform-3fv
   #:uniform-3i
   #:uniform-3iv
   #:uniform-4f
   #:uniform-4fv
   #:uniform-4i
   #:uniform-4iv
   #:uniform-matrix-2fv
   #:uniform-matrix-3fv
   #:uniform-matrix-4fv
   #:use-program
   #:validate-program
   #:vertex-attrib-1f
   #:vertex-attrib-1fv
   #:vertex-attrib-2f
   #:vertex-attrib-2fv
   #:vertex-attrib-3f
   #:vertex-attrib-3fv
   #:vertex-attrib-4f
   #:vertex-attrib-4fv
   #:vertex-attrib-pointer
   #:viewport
   #:+ACTIVE-ATTRIBUTES+
   #:+ACTIVE-TEXTURE+
   #:+ACTIVE-UNIFORMS+
   #:+ALIASED-LINE-WIDTH-RANGE+
   #:+ALIASED-POINT-SIZE-RANGE+
   #:+ALPHA+
   #:+ALPHA-BITS+
   #:+ALWAYS+
   #:+ARRAY-BUFFER+
   #:+ARRAY-BUFFER-BINDING+
   #:+ATTACHED-SHADERS+
   #:+BACK+
   #:+BLEND+
   #:+BLEND-COLOR+
   #:+BLEND-DST-ALPHA+
   #:+BLEND-DST-RGB+
   #:+BLEND-EQUATION+
   #:+BLEND-EQUATION-ALPHA+
   #:+BLEND-EQUATION-RGB+
   #:+BLEND-SRC-ALPHA+
   #:+BLEND-SRC-RGB+
   #:+BLUE-BITS+
   #:+BOOL+
   #:+BOOL-VEC2+
   #:+BOOL-VEC3+
   #:+BOOL-VEC4+
   #:+BROWSER-DEFAULT-WEBGL+
   #:+BUFFER-SIZE+
   #:+BUFFER-USAGE+
   #:+BYTE+
   #:+CCW+
   #:+CLAMP-TO-EDGE+
   #:+COLOR-ATTACHMENT0+
   #:+COLOR-BUFFER-BIT+
   #:+COLOR-CLEAR-VALUE+
   #:+COLOR-WRITEMASK+
   #:+COMPILE-STATUS+
   #:+COMPRESSED-TEXTURE-FORMATS+
   #:+CONSTANT-ALPHA+
   #:+CONSTANT-COLOR+
   #:+CONTEXT-LOST-WEBGL+
   #:+CULL-FACE+
   #:+CULL-FACE-MODE+
   #:+CURRENT-PROGRAM+
   #:+CURRENT-VERTEX-ATTRIB+
   #:+CW+
   #:+DECR+
   #:+DECR-WRAP+
   #:+DELETE-STATUS+
   #:+DEPTH-ATTACHMENT+
   #:+DEPTH-BITS+
   #:+DEPTH-BUFFER-BIT+
   #:+DEPTH-CLEAR-VALUE+
   #:+DEPTH-COMPONENT+
   #:+DEPTH-COMPONENT16+
   #:+DEPTH-FUNC+
   #:+DEPTH-RANGE+
   #:+DEPTH-STENCIL+
   #:+DEPTH-STENCIL-ATTACHMENT+
   #:+DEPTH-TEST+
   #:+DEPTH-WRITEMASK+
   #:+DITHER+
   #:+DONT-CARE+
   #:+DST-ALPHA+
   #:+DST-COLOR+
   #:+DYNAMIC-DRAW+
   #:+ELEMENT-ARRAY-BUFFER+
   #:+ELEMENT-ARRAY-BUFFER-BINDING+
   #:+EQUAL+
   #:+FASTEST+
   #:+FLOAT+
   #:+FLOAT-MAT2+
   #:+FLOAT-MAT3+
   #:+FLOAT-MAT4+
   #:+FLOAT-VEC2+
   #:+FLOAT-VEC3+
   #:+FLOAT-VEC4+
   #:+FRAGMENT-SHADER+
   #:+FRAMEBUFFER+
   #:+FRAMEBUFFER-ATTACHMENT-OBJECT-NAME+
   #:+FRAMEBUFFER-ATTACHMENT-OBJECT-TYPE+
   #:+FRAMEBUFFER-ATTACHMENT-TEXTURE-CUBE-MAP-FACE+
   #:+FRAMEBUFFER-ATTACHMENT-TEXTURE-LEVEL+
   #:+FRAMEBUFFER-BINDING+
   #:+FRAMEBUFFER-COMPLETE+
   #:+FRAMEBUFFER-INCOMPLETE-ATTACHMENT+
   #:+FRAMEBUFFER-INCOMPLETE-DIMENSIONS+
   #:+FRAMEBUFFER-INCOMPLETE-MISSING-ATTACHMENT+
   #:+FRAMEBUFFER-UNSUPPORTED+
   #:+FRONT+
   #:+FRONT-AND-BACK+
   #:+FRONT-FACE+
   #:+FUNC-ADD+
   #:+FUNC-REVERSE-SUBTRACT+
   #:+FUNC-SUBTRACT+
   #:+GENERATE-MIPMAP-HINT+
   #:+GEQUAL+
   #:+GREATER+
   #:+GREEN-BITS+
   #:+HIGH-FLOAT+
   #:+HIGH-INT+
   #:+INCR+
   #:+INCR-WRAP+
   #:+INT+
   #:+INT-VEC2+
   #:+INT-VEC3+
   #:+INT-VEC4+
   #:+INVALID-ENUM+
   #:+INVALID-FRAMEBUFFER-OPERATION+
   #:+INVALID-OPERATION+
   #:+INVALID-VALUE+
   #:+INVERT+
   #:+KEEP+
   #:+LEQUAL+
   #:+LESS+
   #:+LINE-LOOP+
   #:+LINE-STRIP+
   #:+LINE-WIDTH+
   #:+LINEAR+
   #:+LINEAR-MIPMAP-LINEAR+
   #:+LINEAR-MIPMAP-NEAREST+
   #:+LINES+
   #:+LINK-STATUS+
   #:+LOW-FLOAT+
   #:+LOW-INT+
   #:+LUMINANCE+
   #:+LUMINANCE-ALPHA+
   #:+MAX-COMBINED-TEXTURE-IMAGE-UNITS+
   #:+MAX-CUBE-MAP-TEXTURE-SIZE+
   #:+MAX-FRAGMENT-UNIFORM-VECTORS+
   #:+MAX-RENDERBUFFER-SIZE+
   #:+MAX-TEXTURE-IMAGE-UNITS+
   #:+MAX-TEXTURE-SIZE+
   #:+MAX-VARYING-VECTORS+
   #:+MAX-VERTEX-ATTRIBS+
   #:+MAX-VERTEX-TEXTURE-IMAGE-UNITS+
   #:+MAX-VERTEX-UNIFORM-VECTORS+
   #:+MAX-VIEWPORT-DIMS+
   #:+MEDIUM-FLOAT+
   #:+MEDIUM-INT+
   #:+MIRRORED-REPEAT+
   #:+NEAREST+
   #:+NEAREST-MIPMAP-LINEAR+
   #:+NEAREST-MIPMAP-NEAREST+
   #:+NEVER+
   #:+NICEST+
   #:+NO-ERROR+
   #:+NONE+
   #:+NOTEQUAL+
   #:+NUM-COMPRESSED-TEXTURE-FORMATS+
   #:+ONE+
   #:+ONE-MINUS-CONSTANT-ALPHA+
   #:+ONE-MINUS-CONSTANT-COLOR+
   #:+ONE-MINUS-DST-ALPHA+
   #:+ONE-MINUS-DST-COLOR+
   #:+ONE-MINUS-SRC-ALPHA+
   #:+ONE-MINUS-SRC-COLOR+
   #:+OUT-OF-MEMORY+
   #:+PACK-ALIGNMENT+
   #:+POINTS+
   #:+POLYGON-OFFSET-FACTOR+
   #:+POLYGON-OFFSET-FILL+
   #:+POLYGON-OFFSET-UNITS+
   #:+RED-BITS+
   #:+RENDERBUFFER+
   #:+RENDERBUFFER-ALPHA-SIZE+
   #:+RENDERBUFFER-BINDING+
   #:+RENDERBUFFER-BLUE-SIZE+
   #:+RENDERBUFFER-DEPTH-SIZE+
   #:+RENDERBUFFER-GREEN-SIZE+
   #:+RENDERBUFFER-HEIGHT+
   #:+RENDERBUFFER-INTERNAL-FORMAT+
   #:+RENDERBUFFER-RED-SIZE+
   #:+RENDERBUFFER-STENCIL-SIZE+
   #:+RENDERBUFFER-WIDTH+
   #:+RENDERER+
   #:+REPEAT+
   #:+REPLACE+
   #:+RGB+
   #:+RGB5-A1+
   #:+RGB565+
   #:+RGBA+
   #:+RGBA4+
   #:+SAMPLE-ALPHA-TO-COVERAGE+
   #:+SAMPLE-BUFFERS+
   #:+SAMPLE-COVERAGE+
   #:+SAMPLE-COVERAGE-INVERT+
   #:+SAMPLE-COVERAGE-VALUE+
   #:+SAMPLER-2D+
   #:+SAMPLER-CUBE+
   #:+SAMPLES+
   #:+SCISSOR-BOX+
   #:+SCISSOR-TEST+
   #:+SHADER-TYPE+
   #:+SHADING-LANGUAGE-VERSION+
   #:+SHORT+
   #:+SRC-ALPHA+
   #:+SRC-ALPHA-SATURATE+
   #:+SRC-COLOR+
   #:+STATIC-DRAW+
   #:+STENCIL-ATTACHMENT+
   #:+STENCIL-BACK-FAIL+
   #:+STENCIL-BACK-FUNC+
   #:+STENCIL-BACK-PASS-DEPTH-FAIL+
   #:+STENCIL-BACK-PASS-DEPTH-PASS+
   #:+STENCIL-BACK-REF+
   #:+STENCIL-BACK-VALUE-MASK+
   #:+STENCIL-BACK-WRITEMASK+
   #:+STENCIL-BITS+
   #:+STENCIL-BUFFER-BIT+
   #:+STENCIL-CLEAR-VALUE+
   #:+STENCIL-FAIL+
   #:+STENCIL-FUNC+
   #:+STENCIL-INDEX+
   #:+STENCIL-INDEX8+
   #:+STENCIL-PASS-DEPTH-FAIL+
   #:+STENCIL-PASS-DEPTH-PASS+
   #:+STENCIL-REF+
   #:+STENCIL-TEST+
   #:+STENCIL-VALUE-MASK+
   #:+STENCIL-WRITEMASK+
   #:+STREAM-DRAW+
   #:+SUBPIXEL-BITS+
   #:+TEXTURE+
   #:+TEXTURE-2D+
   #:+TEXTURE-BINDING-2D+
   #:+TEXTURE-BINDING-CUBE-MAP+
   #:+TEXTURE-CUBE-MAP+
   #:+TEXTURE-CUBE-MAP-NEGATIVE-X+
   #:+TEXTURE-CUBE-MAP-NEGATIVE-Y+
   #:+TEXTURE-CUBE-MAP-NEGATIVE-Z+
   #:+TEXTURE-CUBE-MAP-POSITIVE-X+
   #:+TEXTURE-CUBE-MAP-POSITIVE-Y+
   #:+TEXTURE-CUBE-MAP-POSITIVE-Z+
   #:+TEXTURE-MAG-FILTER+
   #:+TEXTURE-MIN-FILTER+
   #:+TEXTURE-WRAP-S+
   #:+TEXTURE-WRAP-T+
   #:+TEXTURE0+
   #:+TEXTURE1+
   #:+TEXTURE10+
   #:+TEXTURE11+
   #:+TEXTURE12+
   #:+TEXTURE13+
   #:+TEXTURE14+
   #:+TEXTURE15+
   #:+TEXTURE16+
   #:+TEXTURE17+
   #:+TEXTURE18+
   #:+TEXTURE19+
   #:+TEXTURE2+
   #:+TEXTURE20+
   #:+TEXTURE21+
   #:+TEXTURE22+
   #:+TEXTURE23+
   #:+TEXTURE24+
   #:+TEXTURE25+
   #:+TEXTURE26+
   #:+TEXTURE27+
   #:+TEXTURE28+
   #:+TEXTURE29+
   #:+TEXTURE3+
   #:+TEXTURE30+
   #:+TEXTURE31+
   #:+TEXTURE4+
   #:+TEXTURE5+
   #:+TEXTURE6+
   #:+TEXTURE7+
   #:+TEXTURE8+
   #:+TEXTURE9+
   #:+TRIANGLE-FAN+
   #:+TRIANGLE-STRIP+
   #:+TRIANGLES+
   #:+UNPACK-ALIGNMENT+
   #:+UNPACK-COLORSPACE-CONVERSION-WEBGL+
   #:+UNPACK-FLIP-Y-WEBGL+
   #:+UNPACK-PREMULTIPLY-ALPHA-WEBGL+
   #:+UNSIGNED-BYTE+
   #:+UNSIGNED-INT+
   #:+UNSIGNED-SHORT+
   #:+UNSIGNED-SHORT-4-4-4-4+
   #:+UNSIGNED-SHORT-5-5-5-1+
   #:+UNSIGNED-SHORT-5-6-5+
   #:+VALIDATE-STATUS+
   #:+VENDOR+
   #:+VERSION+
   #:+VERTEX-ATTRIB-ARRAY-BUFFER-BINDING+
   #:+VERTEX-ATTRIB-ARRAY-ENABLED+
   #:+VERTEX-ATTRIB-ARRAY-NORMALIZED+
   #:+VERTEX-ATTRIB-ARRAY-POINTER+
   #:+VERTEX-ATTRIB-ARRAY-SIZE+
   #:+VERTEX-ATTRIB-ARRAY-STRIDE+
   #:+VERTEX-ATTRIB-ARRAY-TYPE+
   #:+VERTEX-SHADER+
   #:+VIEWPORT+
   #:+ZERO+
   ;;
   ))

;; todo:
;; move higher level wrappers into a webgl-ps-implementation: package
;; then use (setf (ps-package-prefix "WEBGL-PS-IMPLEMENTATION") "WPS.")
;; or something to scope the functions to a specific object in JS size
;; -- or maybe a separate webgl-ps-api that exports the public functions
;; that should be scoped to the object? since we don't want local name
;; in the implementation to have the prefix, just the public api...
;; ---- actually, possibly want implementation package as separate one,
;; but don't import symbols into webgl-ps: so implementation package
;; gets unqualified names unless it explicitly qualifies them...
;; ------ actually^2, i guess that doesn't work right either, since we
;; want arglist support on the main API functions, so probably back to
;; api package with names that should be qualified, and define functions
;; outside the scope object (which we probably want anyway for interactive
;; dev)... not sure if we need separate impl. package or if webgl-ps
;; works... separate implementation package might be nicer, since it would
;; allow for easy use of both scope-prefixed and bare versions of same name
;; (with explicit prefix for public api package and not importing it into
;;  impl)
(defpackage #:webgl-ps-api
  (:use :cl :ps :webgl-bindings)
  (:export #:*wps*
           #:clog
           #:init-webgl
           #:request-animation-frame))

(setf (ps:ps-package-prefix '#:webgl-ps-api) "WPS.")

(defpackage #:webgl-ps
  (:use :cl :ps :webgl-bindings)
  #-package-local-nicknames
  (:nicknames #:webgl #:gl)
  #+package-local-nicknames 
  (:local-nicknames (#:api #:webgl-ps-api))
  (:export
   #:active-texture
   #:attach-shader
   #:bind-attrib-location
   #:bind-buffer
   #:bind-framebuffer
   #:bind-renderbuffer
   #:bind-texture
   #:blend-color
   #:blend-equation
   #:blend-equation-separate
   #:blend-func
   #:blend-func-separate
   #:buffer-data
   #:buffer-sub-data
   #:canvas
   #:check-framebuffer-status
   #:clear
   #:clear-color
   #:clear-depth
   #:clear-stencil
   #:color-mask
   #:compile-shader
   #:copy-tex-image-2d
   #:copy-tex-sub-image-2d
   #:create-buffer
   #:create-framebuffer
   #:create-program
   #:create-renderbuffer
   #:create-shader
   #:create-texture
   #:cull-face
   #:delete-buffer
   #:delete-framebuffer
   #:delete-program
   #:delete-renderbuffer
   #:delete-shader
   #:delete-texture
   #:depth-func
   #:depth-mask
   #:depth-range
   #:detach-shader
   #:disable
   #:disable-vertex-attrib-array
   #:draw-arrays
   #:draw-elements
   #:drawing-buffer-height
   #:drawing-buffer-width
   #:enable
   #:enable-vertex-attrib-array
   #:finish
   #:flush
   #:framebuffer-renderbuffer
   #:framebuffer-texture-2d
   #:front-face
   #:generate-mipmap
   #:get-active-attrib
   #:get-active-uniform
   #:get-attached-shaders
   #:get-attrib-location
   #:get-buffer-parameter
   #:get-context-attributes
   #:get-error
   #:get-extension
   #:get-framebuffer-attachment-parameter
   #:get-parameter
   #:get-program-info-log
   #:get-program-parameter
   #:get-renderbuffer-parameter
   #:get-shader-info-log
   #:get-shader-parameter
   #:get-shader-source
   #:get-supported-extensions
   #:get-tex-parameter
   #:get-uniform
   #:get-uniform-location
   #:get-vertex-attrib
   #:get-vertex-attrib-offset
   #:hint
   #:is-buffer
   #:is-context-lost
   #:is-enabled
   #:is-framebuffer
   #:is-program
   #:is-renderbuffer
   #:is-shader
   #:is-texture
   #:line-width
   #:link-program
   #:pixel-store-i
   #:polygon-offset
   #:read-pixels
   #:renderbuffer-storage
   #:sample-coverage
   #:scissor
   #:shader-source
   #:stencil-func
   #:stencil-func-separate
   #:stencil-mask
   #:stencil-mask-separate
   #:stencil-op
   #:stencil-op-separate
   #:tex-image-2d*
   #:tex-image-2d
   #:tex-image2d ;; fixme: delete
   #:tex-parameter-f
   #:tex-parameter-i
   #:tex-sub-image-2d
   #:uniform-1f
   #:uniform-1fv
   #:uniform-1i
   #:uniform-1iv
   #:uniform-2f
   #:uniform-2fv
   #:uniform-2i
   #:uniform-2iv
   #:uniform-3f
   #:uniform-3fv
   #:uniform-3i
   #:uniform-3iv
   #:uniform-4f
   #:uniform-4fv
   #:uniform-4i
   #:uniform-4iv
   #:uniform-matrix-2fv
   #:uniform-matrix-3fv
   #:uniform-matrix-4fv
   #:use-program
   #:validate-program
   #:vertex-attrib-1f
   #:vertex-attrib-1fv
   #:vertex-attrib-2f
   #:vertex-attrib-2fv
   #:vertex-attrib-3f
   #:vertex-attrib-3fv
   #:vertex-attrib-4f
   #:vertex-attrib-4fv
   #:vertex-attrib-pointer
   #:viewport
   #:+ACTIVE-ATTRIBUTES+
   #:+ACTIVE-TEXTURE+
   #:+ACTIVE-UNIFORMS+
   #:+ALIASED-LINE-WIDTH-RANGE+
   #:+ALIASED-POINT-SIZE-RANGE+
   #:+ALPHA+
   #:+ALPHA-BITS+
   #:+ALWAYS+
   #:+ARRAY-BUFFER+
   #:+ARRAY-BUFFER-BINDING+
   #:+ATTACHED-SHADERS+
   #:+BACK+
   #:+BLEND+
   #:+BLEND-COLOR+
   #:+BLEND-DST-ALPHA+
   #:+BLEND-DST-RGB+
   #:+BLEND-EQUATION+
   #:+BLEND-EQUATION-ALPHA+
   #:+BLEND-EQUATION-RGB+
   #:+BLEND-SRC-ALPHA+
   #:+BLEND-SRC-RGB+
   #:+BLUE-BITS+
   #:+BOOL+
   #:+BOOL-VEC2+
   #:+BOOL-VEC3+
   #:+BOOL-VEC4+
   #:+BROWSER-DEFAULT-WEBGL+
   #:+BUFFER-SIZE+
   #:+BUFFER-USAGE+
   #:+BYTE+
   #:+CCW+
   #:+CLAMP-TO-EDGE+
   #:+COLOR-ATTACHMENT0+
   #:+COLOR-BUFFER-BIT+
   #:+COLOR-CLEAR-VALUE+
   #:+COLOR-WRITEMASK+
   #:+COMPILE-STATUS+
   #:+COMPRESSED-TEXTURE-FORMATS+
   #:+CONSTANT-ALPHA+
   #:+CONSTANT-COLOR+
   #:+CONTEXT-LOST-WEBGL+
   #:+CULL-FACE+
   #:+CULL-FACE-MODE+
   #:+CURRENT-PROGRAM+
   #:+CURRENT-VERTEX-ATTRIB+
   #:+CW+
   #:+DECR+
   #:+DECR-WRAP+
   #:+DELETE-STATUS+
   #:+DEPTH-ATTACHMENT+
   #:+DEPTH-BITS+
   #:+DEPTH-BUFFER-BIT+
   #:+DEPTH-CLEAR-VALUE+
   #:+DEPTH-COMPONENT+
   #:+DEPTH-COMPONENT16+
   #:+DEPTH-FUNC+
   #:+DEPTH-RANGE+
   #:+DEPTH-STENCIL+
   #:+DEPTH-STENCIL-ATTACHMENT+
   #:+DEPTH-TEST+
   #:+DEPTH-WRITEMASK+
   #:+DITHER+
   #:+DONT-CARE+
   #:+DST-ALPHA+
   #:+DST-COLOR+
   #:+DYNAMIC-DRAW+
   #:+ELEMENT-ARRAY-BUFFER+
   #:+ELEMENT-ARRAY-BUFFER-BINDING+
   #:+EQUAL+
   #:+FASTEST+
   #:+FLOAT+
   #:+FLOAT-MAT2+
   #:+FLOAT-MAT3+
   #:+FLOAT-MAT4+
   #:+FLOAT-VEC2+
   #:+FLOAT-VEC3+
   #:+FLOAT-VEC4+
   #:+FRAGMENT-SHADER+
   #:+FRAMEBUFFER+
   #:+FRAMEBUFFER-ATTACHMENT-OBJECT-NAME+
   #:+FRAMEBUFFER-ATTACHMENT-OBJECT-TYPE+
   #:+FRAMEBUFFER-ATTACHMENT-TEXTURE-CUBE-MAP-FACE+
   #:+FRAMEBUFFER-ATTACHMENT-TEXTURE-LEVEL+
   #:+FRAMEBUFFER-BINDING+
   #:+FRAMEBUFFER-COMPLETE+
   #:+FRAMEBUFFER-INCOMPLETE-ATTACHMENT+
   #:+FRAMEBUFFER-INCOMPLETE-DIMENSIONS+
   #:+FRAMEBUFFER-INCOMPLETE-MISSING-ATTACHMENT+
   #:+FRAMEBUFFER-UNSUPPORTED+
   #:+FRONT+
   #:+FRONT-AND-BACK+
   #:+FRONT-FACE+
   #:+FUNC-ADD+
   #:+FUNC-REVERSE-SUBTRACT+
   #:+FUNC-SUBTRACT+
   #:+GENERATE-MIPMAP-HINT+
   #:+GEQUAL+
   #:+GREATER+
   #:+GREEN-BITS+
   #:+HIGH-FLOAT+
   #:+HIGH-INT+
   #:+INCR+
   #:+INCR-WRAP+
   #:+INT+
   #:+INT-VEC2+
   #:+INT-VEC3+
   #:+INT-VEC4+
   #:+INVALID-ENUM+
   #:+INVALID-FRAMEBUFFER-OPERATION+
   #:+INVALID-OPERATION+
   #:+INVALID-VALUE+
   #:+INVERT+
   #:+KEEP+
   #:+LEQUAL+
   #:+LESS+
   #:+LINE-LOOP+
   #:+LINE-STRIP+
   #:+LINE-WIDTH+
   #:+LINEAR+
   #:+LINEAR-MIPMAP-LINEAR+
   #:+LINEAR-MIPMAP-NEAREST+
   #:+LINES+
   #:+LINK-STATUS+
   #:+LOW-FLOAT+
   #:+LOW-INT+
   #:+LUMINANCE+
   #:+LUMINANCE-ALPHA+
   #:+MAX-COMBINED-TEXTURE-IMAGE-UNITS+
   #:+MAX-CUBE-MAP-TEXTURE-SIZE+
   #:+MAX-FRAGMENT-UNIFORM-VECTORS+
   #:+MAX-RENDERBUFFER-SIZE+
   #:+MAX-TEXTURE-IMAGE-UNITS+
   #:+MAX-TEXTURE-SIZE+
   #:+MAX-VARYING-VECTORS+
   #:+MAX-VERTEX-ATTRIBS+
   #:+MAX-VERTEX-TEXTURE-IMAGE-UNITS+
   #:+MAX-VERTEX-UNIFORM-VECTORS+
   #:+MAX-VIEWPORT-DIMS+
   #:+MEDIUM-FLOAT+
   #:+MEDIUM-INT+
   #:+MIRRORED-REPEAT+
   #:+NEAREST+
   #:+NEAREST-MIPMAP-LINEAR+
   #:+NEAREST-MIPMAP-NEAREST+
   #:+NEVER+
   #:+NICEST+
   #:+NO-ERROR+
   #:+NONE+
   #:+NOTEQUAL+
   #:+NUM-COMPRESSED-TEXTURE-FORMATS+
   #:+ONE+
   #:+ONE-MINUS-CONSTANT-ALPHA+
   #:+ONE-MINUS-CONSTANT-COLOR+
   #:+ONE-MINUS-DST-ALPHA+
   #:+ONE-MINUS-DST-COLOR+
   #:+ONE-MINUS-SRC-ALPHA+
   #:+ONE-MINUS-SRC-COLOR+
   #:+OUT-OF-MEMORY+
   #:+PACK-ALIGNMENT+
   #:+POINTS+
   #:+POLYGON-OFFSET-FACTOR+
   #:+POLYGON-OFFSET-FILL+
   #:+POLYGON-OFFSET-UNITS+
   #:+RED-BITS+
   #:+RENDERBUFFER+
   #:+RENDERBUFFER-ALPHA-SIZE+
   #:+RENDERBUFFER-BINDING+
   #:+RENDERBUFFER-BLUE-SIZE+
   #:+RENDERBUFFER-DEPTH-SIZE+
   #:+RENDERBUFFER-GREEN-SIZE+
   #:+RENDERBUFFER-HEIGHT+
   #:+RENDERBUFFER-INTERNAL-FORMAT+
   #:+RENDERBUFFER-RED-SIZE+
   #:+RENDERBUFFER-STENCIL-SIZE+
   #:+RENDERBUFFER-WIDTH+
   #:+RENDERER+
   #:+REPEAT+
   #:+REPLACE+
   #:+RGB+
   #:+RGB5-A1+
   #:+RGB565+
   #:+RGBA+
   #:+RGBA4+
   #:+SAMPLE-ALPHA-TO-COVERAGE+
   #:+SAMPLE-BUFFERS+
   #:+SAMPLE-COVERAGE+
   #:+SAMPLE-COVERAGE-INVERT+
   #:+SAMPLE-COVERAGE-VALUE+
   #:+SAMPLER-2D+
   #:+SAMPLER-CUBE+
   #:+SAMPLES+
   #:+SCISSOR-BOX+
   #:+SCISSOR-TEST+
   #:+SHADER-TYPE+
   #:+SHADING-LANGUAGE-VERSION+
   #:+SHORT+
   #:+SRC-ALPHA+
   #:+SRC-ALPHA-SATURATE+
   #:+SRC-COLOR+
   #:+STATIC-DRAW+
   #:+STENCIL-ATTACHMENT+
   #:+STENCIL-BACK-FAIL+
   #:+STENCIL-BACK-FUNC+
   #:+STENCIL-BACK-PASS-DEPTH-FAIL+
   #:+STENCIL-BACK-PASS-DEPTH-PASS+
   #:+STENCIL-BACK-REF+
   #:+STENCIL-BACK-VALUE-MASK+
   #:+STENCIL-BACK-WRITEMASK+
   #:+STENCIL-BITS+
   #:+STENCIL-BUFFER-BIT+
   #:+STENCIL-CLEAR-VALUE+
   #:+STENCIL-FAIL+
   #:+STENCIL-FUNC+
   #:+STENCIL-INDEX+
   #:+STENCIL-INDEX8+
   #:+STENCIL-PASS-DEPTH-FAIL+
   #:+STENCIL-PASS-DEPTH-PASS+
   #:+STENCIL-REF+
   #:+STENCIL-TEST+
   #:+STENCIL-VALUE-MASK+
   #:+STENCIL-WRITEMASK+
   #:+STREAM-DRAW+
   #:+SUBPIXEL-BITS+
   #:+TEXTURE+
   #:+TEXTURE-2D+
   #:+TEXTURE-BINDING-2D+
   #:+TEXTURE-BINDING-CUBE-MAP+
   #:+TEXTURE-CUBE-MAP+
   #:+TEXTURE-CUBE-MAP-NEGATIVE-X+
   #:+TEXTURE-CUBE-MAP-NEGATIVE-Y+
   #:+TEXTURE-CUBE-MAP-NEGATIVE-Z+
   #:+TEXTURE-CUBE-MAP-POSITIVE-X+
   #:+TEXTURE-CUBE-MAP-POSITIVE-Y+
   #:+TEXTURE-CUBE-MAP-POSITIVE-Z+
   #:+TEXTURE-MAG-FILTER+
   #:+TEXTURE-MIN-FILTER+
   #:+TEXTURE-WRAP-S+
   #:+TEXTURE-WRAP-T+
   #:+TEXTURE0+
   #:+TEXTURE1+
   #:+TEXTURE10+
   #:+TEXTURE11+
   #:+TEXTURE12+
   #:+TEXTURE13+
   #:+TEXTURE14+
   #:+TEXTURE15+
   #:+TEXTURE16+
   #:+TEXTURE17+
   #:+TEXTURE18+
   #:+TEXTURE19+
   #:+TEXTURE2+
   #:+TEXTURE20+
   #:+TEXTURE21+
   #:+TEXTURE22+
   #:+TEXTURE23+
   #:+TEXTURE24+
   #:+TEXTURE25+
   #:+TEXTURE26+
   #:+TEXTURE27+
   #:+TEXTURE28+
   #:+TEXTURE29+
   #:+TEXTURE3+
   #:+TEXTURE30+
   #:+TEXTURE31+
   #:+TEXTURE4+
   #:+TEXTURE5+
   #:+TEXTURE6+
   #:+TEXTURE7+
   #:+TEXTURE8+
   #:+TEXTURE9+
   #:+TRIANGLE-FAN+
   #:+TRIANGLE-STRIP+
   #:+TRIANGLES+
   #:+UNPACK-ALIGNMENT+
   #:+UNPACK-COLORSPACE-CONVERSION-WEBGL+
   #:+UNPACK-FLIP-Y-WEBGL+
   #:+UNPACK-PREMULTIPLY-ALPHA-WEBGL+
   #:+UNSIGNED-BYTE+
   #:+UNSIGNED-INT+
   #:+UNSIGNED-SHORT+
   #:+UNSIGNED-SHORT-4-4-4-4+
   #:+UNSIGNED-SHORT-5-5-5-1+
   #:+UNSIGNED-SHORT-5-6-5+
   #:+VALIDATE-STATUS+
   #:+VENDOR+
   #:+VERSION+
   #:+VERTEX-ATTRIB-ARRAY-BUFFER-BINDING+
   #:+VERTEX-ATTRIB-ARRAY-ENABLED+
   #:+VERTEX-ATTRIB-ARRAY-NORMALIZED+
   #:+VERTEX-ATTRIB-ARRAY-POINTER+
   #:+VERTEX-ATTRIB-ARRAY-SIZE+
   #:+VERTEX-ATTRIB-ARRAY-STRIDE+
   #:+VERTEX-ATTRIB-ARRAY-TYPE+
   #:+VERTEX-SHADER+
   #:+VIEWPORT+
   #:+ZERO+
   #:init-webgl
   ;; from api
   #:clog
   #:init-webgl
   #:request-animation-frame
   ;;
   ))

